version: "3.8"
services:
  app:
    build: .
    command: bundle exec rackup --host 0.0.0.0 -p 4000
    ports:
      - "4000:4000"
    volumes:
      - .:/src

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: s_torello
      POSTGRES_USER: Ivan
      POSTGRES_PASSWORD: IvanRootPeruchin
    ports:
      - "5432:5432"