require_relative '../models/item'


Item.create(name: 'conjunto', price: 4500, category: 'lenceria', image: '/front/lenceria/lenceria-1.jpeg', in_stock: true)
Item.create(name: 'conjunto', price: 4200, category: 'lenceria', image: '/front/lenceria/lenceria-2.jpeg', in_stock: true)
Item.create(name: 'conjunto', price: 2000, category: 'lenceria', image: '/front/lenceria/lenceria-3.jpeg', in_stock: false)
Item.create(name: 'conjunto', price: 3200, category: 'lenceria', image: '/front/lenceria/lenceria-4.jpeg', in_stock: true)
Item.create(name: 'conjunto', price: 500, category: 'lenceria', image: '/front/lenceria/lenceria-5.jpeg', in_stock: true)
Item.create(name: 'body', price: 9000, category: 'lenceria', image: '/front/lenceria/lenceria-6.jpeg', in_stock: true)
Item.create(name: 'body', price: 6000, category: 'lenceria', image: '/front/lenceria/lenceria-7.jpeg', in_stock: false)
Item.create(name: 'body', price: 1200, category: 'lenceria', image: '/front/lenceria/lenceria-8.jpeg', in_stock: true)
Item.create(name: 'conjunto', price: 1500, category: 'lenceria', image: '/front/lenceria/lenceria-9.jpeg', in_stock: true)

Item.create(name: 'Calza', price: 9500, category: 'sport', image: '/front/sport/sport-1.jpeg', in_stock: true)
Item.create(name: 'Remeron', price: 1500, category: 'sport', image: '/front/sport/sport-2.jpeg', in_stock: true)
Item.create(name: 'Musculosa', price: 4700, category: 'sport', image: '/front/sport/sport-3.jpeg', in_stock: false)
Item.create(name: 'Conjunto', price: 32000, category: 'sport', image: '/front/sport/sport-4.jpeg', in_stock: true)
Item.create(name: 'Top deportivo', price: 400, category: 'sport', image: '/front/sport/sport-5.jpeg', in_stock: true)
Item.create(name: 'Top + Calza', price: 450, category: 'sport', image: '/front/sport/sport-6.jpeg', in_stock: true)
Item.create(name: 'Calza', price: 45000, category: 'sport', image: '/front/sport/sport-7.jpeg', in_stock: false)
Item.create(name: 'Calza', price: 4500.50, category: 'sport', image: '/front/sport/sport-8.jpeg', in_stock: true)
Item.create(name: 'Musculosa', price: 6890, category: 'sport', image: '/front/sport/sport-9.jpeg', in_stock: true)

Color.create(name: 'Azul')
Color.create(name: 'Blanco')
Color.create(name: 'Rosa')
Color.create(name: 'Rojo')
Color.create(name: 'Negro')
Color.create(name: 'Verde')
Color.create(name: 'Celeste')
Color.create(name: 'Amarillo')
Color.create(name: 'Violeta')
Color.create(name: 'Beige')

Size.create(number: 'S')
Size.create(number: 'M')
Size.create(number: 'L')
Size.create(number: 'XL')
Size.create(number: 'XXL')
Size.create(number: '1')
Size.create(number: '2')
Size.create(number: '3')
Size.create(number: '4')
Size.create(number: '5')
Size.create(number: '6')
Size.create(number: '80')
Size.create(number: '90')
Size.create(number: '100')
Size.create(number: '110')
Size.create(number: '120')
